import csv

batch3_cards = [
    # --- ADVANCED WINDOWING & AGGREGATIONS ---
    {
        "Question": "What is the difference between `ROLLUP`, `CUBE`, and `GROUPING SETS` in SQL?",
        "Answer": "<b>ANSWER:</b> Hierarchical vs. Multi-dimensional aggregations.<br><br>• <b>`GROUPING SETS`:</b> Computes specific designated groupings in a single query.<br>• <b>`ROLLUP (year, quarter, month)`:</b> Hierarchical subtotals (Year+Quarter+Month, Year+Quarter, Year, Grand Total).<br>• <b>`CUBE (region, product)`:</b> Computes ALL $2^N$ possible permutations and cross-tabulations.",
        "Topic": "Analytical SQL",
        "Tags": "sql aggregations rollup cube grouping_sets"
    },
    {
        "Question": "What does the `GROUPING()` function do in subtotal queries?",
        "Answer": "<b>ANSWER:</b> Distinguishes between subtotal NULLs and genuine data NULLs.<br><br>Returns `1` if a NULL was generated by a `ROLLUP`/`CUBE` subtotal, and `0` if the row actually contains a NULL value in the database. Used to replace subtotal NULLs with labels: <code>CASE WHEN GROUPING(dept) = 1 THEN 'All Departments' ELSE dept END</code>.",
        "Topic": "Analytical SQL",
        "Tags": "sql aggregations grouping subtotals"
    },
    {
        "Question": "What is `PERCENT_RANK()` and how is it calculated?",
        "Answer": "<b>ANSWER:</b> Evaluates the relative rank of a row on a scale from 0.0 to 1.0.<br><br><b>Formula:</b><br><code>PERCENT_RANK() = (RANK() - 1) / (Total Rows - 1)</code><br>The top row receives `0.0`, and the bottom row receives `1.0`.",
        "Topic": "Window Functions",
        "Tags": "sql window_functions percent_rank statistics"
    },
    {
        "Question": "What is `NTH_VALUE(col, n)` in SQL window functions?",
        "Answer": "<b>ANSWER:</b> Returns the value of the $n$-th row in the window frame.<br><br><b>Example:</b><br><code>NTH_VALUE(salary, 2) OVER (PARTITION BY dept ORDER BY salary DESC)</code><br>Returns the 2nd highest salary in each department.",
        "Topic": "Window Functions",
        "Tags": "sql window_functions nth_value"
    },

    # --- RECURSIVE CTES & ADVANCED DDL/DML ---
    {
        "Question": "How do you traverse an Employee-Manager hierarchy from Top to Bottom using a Recursive CTE?",
        "Answer": "<b>ANSWER:</b> Start with the CEO and recursively join where `e.manager_id = cte.id`.<br><br><b>The SQL:</b><br><code>WITH RECURSIVE org AS ( <br>    SELECT id, name, manager_id, 1 AS level FROM emp WHERE manager_id IS NULL <br>    UNION ALL <br>    SELECT e.id, e.name, e.manager_id, o.level + 1 <br>    FROM emp e JOIN org o ON e.manager_id = o.id <br>) <br>SELECT * FROM org;</code>",
        "Topic": "CTEs & Subqueries",
        "Tags": "sql cte recursive hierarchy org_chart"
    },
    {
        "Question": "How do you prevent infinite loops in Recursive CTEs with circular data?",
        "Answer": "<b>ANSWER:</b> Add a depth limit or use `CYCLE` detection.<br><br><b>Safe Approach:</b> Add a level check: <code>WHERE level < 20</code>.<br>In PostgreSQL 14+, use the native syntax: <code>CYCLE id SET is_cycle USING path</code> to automatically halt recursion if a loop is encountered.",
        "Topic": "CTEs & Subqueries",
        "Tags": "sql cte recursive cycle infinite_loop"
    },
    {
        "Question": "What is a Data-Modifying CTE in PostgreSQL?",
        "Answer": "<b>ANSWER:</b> A CTE that performs `INSERT`, `UPDATE`, or `DELETE` with `RETURNING`.<br><br><b>The SQL:</b><br><code>WITH archived_orders AS ( <br>    DELETE FROM orders WHERE order_date < '2020-01-01' RETURNING * <br>) <br>INSERT INTO orders_history SELECT * FROM archived_orders;</code><br>Atomically moves millions of rows in a single statement without application code.",
        "Topic": "CTEs & Subqueries",
        "Tags": "sql postgres cte dml returning archive"
    },
    {
        "Question": "How does an 'Upsert' (`ON CONFLICT DO UPDATE`) work in PostgreSQL?",
        "Answer": "<b>ANSWER:</b> Inserts a new row, or updates the existing row if a unique key conflicts.<br><br><b>The SQL:</b><br><code>INSERT INTO user_stats (user_id, login_count) VALUES (101, 1) <br>ON CONFLICT (user_id) <br>DO UPDATE SET login_count = user_stats.login_count + 1;</code><br>Completely atomic and safe against concurrent race conditions.",
        "Topic": "Advanced DML",
        "Tags": "sql postgres upsert on_conflict insert"
    },
    {
        "Question": "What is the `RETURNING` clause in PostgreSQL?",
        "Answer": "<b>ANSWER:</b> Immediately returns values from rows created or modified by `INSERT`, `UPDATE`, or `DELETE`.<br><br><b>Example:</b><br><code>INSERT INTO users (name, email) VALUES ('Alice', 'a@b.com') RETURNING id;</code><br>Eliminates a second round-trip `SELECT` to fetch auto-generated primary keys.",
        "Topic": "Advanced DML",
        "Tags": "sql postgres returning dml performance"
    },

    # --- ADVANCED JOINS & SARGABILITY ---
    {
        "Question": "How do you find unique pairs of items without generating duplicate reciprocal pairs (A, B) and (B, A)?",
        "Answer": "<b>ANSWER:</b> Use a Self-Join with an inequality condition `a.id < b.id`.<br><br><b>The SQL:</b><br><code>SELECT a.name, b.name FROM products a <br>JOIN products b ON a.category_id = b.category_id AND a.id < b.id;</code><br>The `<` prevents self-matches (`a.id = b.id`) and duplicate reversed pairs.",
        "Topic": "Joins & Set Operations",
        "Tags": "sql joins self_join pairs inequality"
    },
    {
        "Question": "Why is indexing Foreign Key columns mandatory in high-throughput OLTP databases?",
        "Answer": "<b>ANSWER:</b> To prevent full table scans and severe table locks when parent rows are deleted or updated.<br><br>If `Orders.customer_id` is NOT indexed, deleting a customer requires Postgres to perform a sequential scan across the entire `Orders` table to verify referential integrity, acquiring heavy table locks.",
        "Topic": "Query Optimization",
        "Tags": "sql indexes foreign_key oltp locks"
    },
    {
        "Question": "Is `WHERE name = TRIM(:input)` SARGable?",
        "Answer": "<b>ANSWER:</b> YES ✅<br><br>Because the function `TRIM()` is executed on the <b>input parameter / constant</b>, not on the table column. The database trims the input once, and uses the standard B-Tree index on `name` to perform a fast Index Seek.",
        "Topic": "Query Optimization",
        "Tags": "sql optimization sargable parameters index"
    },
    {
        "Question": "Why is `WHERE first_name || ' ' || last_name = 'John Doe'` non-SARGable?",
        "Answer": "<b>ANSWER:</b> Concatenating columns creates an expression that cannot use individual column indexes.<br><br><b>Non-SARGable:</b> <code>WHERE first_name || ' ' || last_name = 'John Doe'</code> (Forces full table scan).<br><b>SARGable Rewrite:</b> <code>WHERE first_name = 'John' AND last_name = 'Doe'</code> (Uses composite index on `(first_name, last_name)`).",
        "Topic": "Query Optimization",
        "Tags": "sql optimization sargable concatenation index"
    },
    {
        "Question": "What is Index Selectivity and when will the optimizer reject an index in favor of a Sequential Scan?",
        "Answer": "<b>ANSWER:</b> The percentage of unique, matching rows retrieved.<br><br><b>Rule of Thumb:</b> If a query matches more than <b>10% to 15%</b> of the total rows in a table, the query planner deliberately ignores the index and performs a Sequential Scan. Reading sequential blocks off disk is faster than bouncing randomly through index pointers for high percentages of rows.",
        "Topic": "Query Optimization",
        "Tags": "sql optimizer selectivity seq_scan index"
    },
    {
        "Question": "Why is building an index on a Boolean column (`true`/`false`) usually a complete waste of storage?",
        "Answer": "<b>ANSWER:</b> Extremely poor selectivity (only 2 distinct values).<br><br>If 50% of rows are `true` and 50% are `false`, the optimizer will NEVER use the index (it will use a Seq Scan).<br><b>Exception:</b> A <b>Partial Index</b> (e.g. `WHERE is_active = false`) is effective if only 0.1% of rows are false.",
        "Topic": "Query Optimization",
        "Tags": "sql indexes boolean selectivity partial_index"
    },
    {
        "Question": "What is the difference between an 'Index Condition' and a 'Filter' in an EXPLAIN plan?",
        "Answer": "<b>ANSWER:</b> Index Seek vs. Post-fetch evaluation.<br><br>• <b>Index Condition:</b> The index was used to jump directly to the target rows (fast B-Tree seek).<br>• <b>Filter:</b> Rows had to be fetched and evaluated individually in memory (slower). Strive to push conditions into the Index Condition.",
        "Topic": "Query Optimization",
        "Tags": "sql explain index_condition filter tuning"
    },
    {
        "Question": "What is a Bitmap Index Scan in PostgreSQL?",
        "Answer": "<b>ANSWER:</b> Combining multiple indexes using in-memory bitwise AND/OR operations.<br><br><b>Example:</b> If you query `WHERE city = 'London' AND age > 50`, Postgres uses an index on `city` to create a bitmap, an index on `age` to create a second bitmap, ANDs them together, and only visits the exact matching data pages on disk.",
        "Topic": "Query Optimization",
        "Tags": "sql postgres bitmap_scan explain optimization"
    },
    {
        "Question": "What does `Sort Method: external merge Disk` indicate in an EXPLAIN plan?",
        "Answer": "<b>ANSWER:</b> The query's sort operation exceeded `work_mem` and spilled to slow disk storage.<br><br><b>Fix:</b> Increase `work_mem` for the query session: <code>SET work_mem = '256MB';</code>, or create an index that matches the `ORDER BY` clause to eliminate sorting entirely.",
        "Topic": "Query Optimization",
        "Tags": "sql explain work_mem sort disk spill"
    },
    {
        "Question": "How do you safely prevent 'Division by Zero' errors in SQL?",
        "Answer": "<b>ANSWER:</b> Use `NULLIF(divisor, 0)`.<br><br><b>The SQL:</b><br><code>SELECT revenue / NULLIF(ad_spend, 0) AS roi <br>FROM marketing_campaigns;</code><br>If `ad_spend = 0`, `NULLIF` turns it into `NULL`. Dividing by NULL returns `NULL` rather than crashing the query with a fatal runtime error.",
        "Topic": "SQL Gotchas",
        "Tags": "sql functions nullif division_by_zero"
    },
    {
        "Question": "How do you calculate a percentage pass rate using `CASE WHEN` inside `AVG()`?",
        "Answer": "<b>ANSWER:</b> Return 1.0 for pass and 0.0 for fail.<br><br><b>The SQL:</b><br><code>SELECT course_id, <br>       AVG(CASE WHEN score >= 50 THEN 1.0 ELSE 0.0 END) * 100 AS pass_percentage <br>FROM exam_results GROUP BY course_id;</code><br>Clean mathematical trick that replaces complex subqueries.",
        "Topic": "Analytical SQL",
        "Tags": "sql analytics case_when avg percentage"
    },
    {
        "Question": "What is the difference between `EXTRACT()`, `DATE_PART()`, and `DATE_TRUNC()` in PostgreSQL?",
        "Answer": "<b>ANSWER:</b> Extracting a numeric subfield vs. Rounding down a timestamp.<br><br>• <b>`EXTRACT(MONTH FROM date)`:</b> Returns a number (e.g. `8` for August).<br>• <b>`DATE_TRUNC('month', date)`:</b> Rounds down to the 1st of the month: `'2024-08-01 00:00:00'`. Essential for monthly trend aggregations in `GROUP BY`.",
        "Topic": "Analytical SQL",
        "Tags": "sql postgres dates date_trunc extract"
    },
    {
        "Question": "How do you query 7 days of historical data using relative interval arithmetic?",
        "Answer": "<b>ANSWER:</b> Subtract an `INTERVAL` from `NOW()`.<br><br><b>The SQL:</b><br><code>SELECT * FROM audit_logs <br>WHERE created_at >= NOW() - INTERVAL '7 days';</code>",
        "Topic": "Analytical SQL",
        "Tags": "sql postgres dates intervals"
    },

    # --- JSONB & MODERN DATA TYPES ---
    {
        "Question": "What is the difference between `JSON` and `JSONB` in PostgreSQL?",
        "Answer": "<b>ANSWER:</b> Raw text string vs. Decomposed binary format.<br><br>• <b>`JSON`:</b> Stores exact plain text (preserves whitespace). Fast to insert, but slow to query because it must be re-parsed on every read.<br>• <b>`JSONB` (Recommended):</b> Decomposed binary storage. Slightly slower to insert, but dramatically faster to query and supports GIN indexing.",
        "Topic": "JSONB & Modern Types",
        "Tags": "sql postgres json jsonb types"
    },
    {
        "Question": "What is the difference between the `->` and `->>` operators in PostgreSQL JSONB?",
        "Answer": "<b>ANSWER:</b> Returning a JSON object vs. Returning plain text.<br><br>• <b>`data -> 'user'`:</b> Returns `{\"name\": \"Alice\"}` as JSONB.<br>• <b>`data ->> 'name'`:</b> Returns `'Alice'` as a standard `TEXT` string for display or string comparisons.",
        "Topic": "JSONB & Modern Types",
        "Tags": "sql postgres jsonb operators"
    },
    {
        "Question": "What does the `@>` containment operator do in PostgreSQL JSONB?",
        "Answer": "<b>ANSWER:</b> Checks if a JSONB document contains a specific key-value pattern.<br><br><b>The SQL:</b><br><code>SELECT * FROM users WHERE profile @> '{\"role\": \"admin\"}';</code><br>Can be accelerated with a standard GIN index for microsecond lookups across millions of complex JSON documents.",
        "Topic": "JSONB & Modern Types",
        "Tags": "sql postgres jsonb containment gin"
    }
]

with open('decks/sql_tuning_deck.csv', 'a', newline='', encoding='utf-8') as f:
    writer = csv.DictWriter(f, fieldnames=["Question", "Answer", "Topic", "Tags"])
    for card in batch3_cards:
        writer.writerow(card)

print(f"Batch 3 complete: appended {len(batch3_cards)} cards to decks/sql_tuning_deck.csv.")
