import csv

cards = [
    # Backup & Recovery
    {"Question": "What are the three main approaches to backing up a Postgres database?", "Answer": "<b>ANSWER:</b> SQL Dump, File System Level Backup, and Continuous Archiving (PITR).<br><br>1. <b>SQL Dump (pg_dump):</b> Logical backup creating SQL statements to recreate data.<br>2. <b>File System Backup:</b> Stopping the DB and copying the raw data files.<br>3. <b>Continuous Archiving / PITR:</b> Taking a base backup and archiving WAL files to allow restoring to any specific second in time.", "Topic": "Backup & Recovery", "Tags": "edb_postgres backup types"},
    {"Question": "What is `pg_dump`?", "Answer": "<b>ANSWER:</b> A utility for Logical Backups.<br><br>It extracts a Postgres database into a script file or archive file. It does <b>not</b> block other users from reading or writing to the database while it runs.", "Topic": "Backup & Recovery", "Tags": "edb_postgres backup pg_dump"},
    {"Question": "How do you backup ALL databases on a Postgres server at once?", "Answer": "<b>ANSWER:</b> Use the `pg_dumpall` utility.<br><br><b>The Code:</b><br><code>pg_dumpall -U postgres > all_dbs_backup.sql</code><br><br>Unlike `pg_dump` which targets one DB, `pg_dumpall` grabs everything, including global objects like Roles and Tablespaces.", "Topic": "Backup & Recovery", "Tags": "edb_postgres backup pg_dumpall"},
    {"Question": "What is WAL Archiving?", "Answer": "<b>ANSWER:</b> Saving old Write-Ahead Logs before they are overwritten.<br><br>By default, Postgres recycles old WAL files. If you enable `archive_mode = on` and set an `archive_command` (e.g., copying the WAL to a remote server or S3), you can keep a permanent record of all transactions.", "Topic": "Backup & Recovery", "Tags": "edb_postgres backup wal archiving"},
    {"Question": "What is PITR (Point-in-Time Recovery)?", "Answer": "<b>ANSWER:</b> Restoring a database to a specific moment in time (e.g., right before someone accidentally dropped a table).<br><br><b>How it works:</b> You restore a physical Base Backup, then Postgres replays the Archived WAL files sequentially, and you tell it to stop at a specific timestamp using `recovery_target_time`.", "Topic": "Backup & Recovery", "Tags": "edb_postgres backup pitr"},
    {"Question": "What does `pg_basebackup` do?", "Answer": "<b>ANSWER:</b> Takes a physical backup of a running database cluster.<br><br>It connects via the replication protocol and safely copies the raw binary files (`$PGDATA`) without needing to shut down the server. This forms the starting point for PITR or setting up a Replica.", "Topic": "Backup & Recovery", "Tags": "edb_postgres backup pg_basebackup"},
    
    # Replication & High Availability
    {"Question": "What is Streaming Replication in Postgres?", "Answer": "<b>ANSWER:</b> Asynchronous Physical Replication.<br><br>The Primary server continuously streams its WAL records over a network connection to one or more Standby servers. The Standbys apply these records to physically match the Primary.", "Topic": "Replication & HA", "Tags": "edb_postgres replication streaming"},
    {"Question": "What is a 'Replication Slot'?", "Answer": "<b>ANSWER:</b> A safety mechanism to prevent the Primary from deleting WAL files before the Standby has received them.<br><br>Without a slot, if the Standby disconnects, the Primary might overwrite old WALs, breaking the replication permanently. With a slot, the Primary holds onto the WALs (consuming disk space) until the Standby reconnects.", "Topic": "Replication & HA", "Tags": "edb_postgres replication slots"},
    {"Question": "What is the difference between Physical and Logical Replication?", "Answer": "<b>ANSWER:</b> Byte-for-byte copy vs SQL-statement copy.<br><br>• <b>Physical (Streaming):</b> Copies exact disk blocks. Standby is 100% identical and Read-Only.<br>• <b>Logical:</b> Replicates actual table data changes (Inserts/Updates). Allows replicating a single table, replicating between different Postgres versions, and the replica can still accept writes to other tables.", "Topic": "Replication & HA", "Tags": "edb_postgres replication physical logical"},
    {"Question": "How do you check replication lag on the Primary server?", "Answer": "<b>ANSWER:</b> Query the `pg_stat_replication` view.<br><br><b>The Code:</b><br><code>SELECT client_addr, state, sent_lsn, write_lsn, replay_lsn <br>FROM pg_stat_replication;</code><br><br>You compare the Primary's WAL location (`sent_lsn`) against the Standby's location (`replay_lsn`).", "Topic": "Replication & HA", "Tags": "edb_postgres replication lag monitoring"},
    {"Question": "What is Synchronous Replication?", "Answer": "<b>ANSWER:</b> Zero Data Loss guarantees.<br><br>Configured via `synchronous_commit = on` and `synchronous_standby_names`. The Primary will <b>pause</b> the client's COMMIT request until the Standby acknowledges it has received and written the WAL. <b>Risk:</b> If the Standby goes offline, the Primary hangs and stops accepting writes.", "Topic": "Replication & HA", "Tags": "edb_postgres replication synchronous"},
    
    # Routine Maintenance
    {"Question": "What does the `VACUUM` command do?", "Answer": "<b>ANSWER:</b> Reclaims storage occupied by dead tuples.<br><br>In Postgres (due to MVCC), updating or deleting a row doesn't remove it physically; it marks it as dead. `VACUUM` scans tables to find these dead rows and marks their disk space as available for future inserts.", "Topic": "Routine Maintenance", "Tags": "edb_postgres maintenance vacuum"},
    {"Question": "What is `VACUUM FULL` and why should you avoid it in production?", "Answer": "<b>ANSWER:</b> It completely rebuilds the table to return disk space to the OS.<br><br><b>The Danger:</b> It requires an exclusive lock (blocking ALL reads and writes) and creates a brand new copy of the table, requiring double the disk space temporarily. Standard `VACUUM` is preferred.", "Topic": "Routine Maintenance", "Tags": "edb_postgres maintenance vacuum full"},
    {"Question": "What does the `ANALYZE` command do?", "Answer": "<b>ANSWER:</b> Updates table statistics for the Query Planner.<br><br>It samples data in tables (e.g., most common values, distribution) and stores it in `pg_statistic`. The Query Planner uses this to decide whether to use an Index Scan or a Sequential Scan.", "Topic": "Routine Maintenance", "Tags": "edb_postgres maintenance analyze planner"},
    {"Question": "What is the Autovacuum Daemon?", "Answer": "<b>ANSWER:</b> A background process that automatically runs `VACUUM` and `ANALYZE`.<br><br>It wakes up periodically, checks `pg_stat_all_tables` for tables with lots of dead tuples or changes, and automatically vacuums them. It is highly recommended to leave this ON in production.", "Topic": "Routine Maintenance", "Tags": "edb_postgres maintenance autovacuum"},
    {"Question": "How do you rebuild a corrupted or bloated index?", "Answer": "<b>ANSWER:</b> Using `REINDEX`.<br><br><b>The Code:</b><br><code>REINDEX INDEX my_index_name;</code><br>Or rebuild all indexes on a table:<br><code>REINDEX TABLE my_table;</code><br>Note: In PG12+, use `REINDEX CONCURRENTLY` to avoid blocking writes.", "Topic": "Routine Maintenance", "Tags": "edb_postgres maintenance reindex"},
    
    # Advanced Tuning & Architecture
    {"Question": "What is Transaction ID (XID) Wraparound?", "Answer": "<b>ANSWER:</b> A catastrophic failure caused by not vacuuming.<br><br>Postgres assigns an integer ID to every transaction. The max is 2 billion. Once it hits 2 billion, it 'wraps around' to 0. If old rows aren't 'frozen' via VACUUM before this happens, Postgres suddenly thinks old rows belong to the future and hides them, resulting in massive data loss. The database will shut down to prevent this if vacuum is ignored.", "Topic": "Postgres Architecture", "Tags": "edb_postgres architecture vacuum xid"},
    {"Question": "What is an Index-Only Scan?", "Answer": "<b>ANSWER:</b> A performance optimization where the query planner gets all requested data directly from the Index, without visiting the Table.<br><br>Example: If you have an index on `(id, email)` and you run `SELECT email FROM users WHERE id = 5;`, it doesn't need to read the table. The Visibility Map must indicate the page is fully visible.", "Topic": "SQL Tuning", "Tags": "edb_postgres tuning indexes scan"},
    {"Question": "What is a Sequential Scan (Seq Scan)?", "Answer": "<b>ANSWER:</b> Scanning the entire table from top to bottom.<br><br>Usually happens when there is no index, or the query planner decides the query will fetch a huge percentage of the table anyway (so reading the table directly is faster than bouncing between the index and table).", "Topic": "SQL Tuning", "Tags": "edb_postgres tuning scan sequential"},
    {"Question": "How do you view the execution plan of a query?", "Answer": "<b>ANSWER:</b> Use the `EXPLAIN` command.<br><br><b>The Code:</b><br><code>EXPLAIN SELECT * FROM users WHERE age > 30;</code><br><br>Use `EXPLAIN ANALYZE` to actually execute the query and show the real execution times versus the estimates.", "Topic": "SQL Tuning", "Tags": "edb_postgres sql tuning explain"}
]

with open('d:/all_codes/anki_cs_it_decks/edb_postgres_deck.csv', 'a', newline='', encoding='utf-8') as f:
    writer = csv.DictWriter(f, fieldnames=["Question", "Answer", "Topic", "Tags"])
    for card in cards:
        writer.writerow(card)

print(f"Appended {len(cards)} cards from Part 3 to the deck.")
