import csv

cards = [
    # Extra 15 advanced cards
    {"Question": "What is `pg_stat_bgwriter`?", "Answer": "<b>ANSWER:</b> A system view for monitoring background writer performance.<br><br>It shows how many buffers were allocated, how many were written by the bgwriter versus individual backends (sessions). If `buffers_backend` is very high, it means the bgwriter isn't keeping up, and you need to tune `bgwriter_delay` or `bgwriter_lru_maxpages`.", "Topic": "Performance Tuning", "Tags": "edb_postgres tuning bgwriter"},
    {"Question": "What is `effective_io_concurrency`?", "Answer": "<b>ANSWER:</b> Tells Postgres how many concurrent disk I/O operations it can expect the storage subsystem to handle.<br><br>For standard HDDs, it's 1. For RAID arrays, it's the number of disks. For modern NVMe SSDs, it should be set high (e.g., 200+). It helps the planner optimize Bitmap Index Scans.", "Topic": "Configuration", "Tags": "edb_postgres config io nvme"},
    {"Question": "How does `random_page_cost` differ between HDD and SSD?", "Answer": "<b>ANSWER:</b> It dictates the planner's bias against Index Scans.<br><br>By default, it's `4.0` (assuming random disk reads are 4x slower than sequential reads, true for HDDs). For SSDs, random reads are almost as fast as sequential reads, so DBAs lower this to `1.1` to encourage the planner to use indexes more often.", "Topic": "Configuration", "Tags": "edb_postgres config ssd random_page_cost"},
    {"Question": "What is a Bitmap Heap Scan?", "Answer": "<b>ANSWER:</b> The middle ground between an Index Scan and a Sequential Scan.<br><br>If a query needs many rows (but not all of them), Postgres scans the index first, builds an in-memory 'bitmap' of which data pages contain the matching rows, and then physically visits the table, sorting the page fetches to avoid random I/O.", "Topic": "Query Tuning", "Tags": "edb_postgres tuning scan bitmap"},
    {"Question": "What is `pg_stat_user_indexes` used for?", "Answer": "<b>ANSWER:</b> Finding unused or useless indexes.<br><br>Indexes speed up reads but slow down writes (Inserts/Updates). If you query `pg_stat_user_indexes` and see `idx_scan = 0` for an index after months of uptime, it means the index is never being used and should be deleted to save space and improve write performance.", "Topic": "Maintenance", "Tags": "edb_postgres maintenance indexes unused"},
    {"Question": "What is a Foreign Key constraint's impact on performance?", "Answer": "<b>ANSWER:</b> It requires a hidden lookup on every INSERT/UPDATE.<br><br>If `Orders` has a Foreign Key pointing to `Users`, every time you insert an Order, Postgres must implicitly run a `SELECT` on `Users` to verify the ID exists. You should <b>always</b> index the Foreign Key column to speed up this check and avoid full table scans during cascading deletes.", "Topic": "Architecture", "Tags": "edb_postgres architecture foreign_key"},
    {"Question": "What happens when `max_connections` is exhausted?", "Answer": "<b>ANSWER:</b> New clients are completely blocked with a \"FATAL: sorry, too many clients already\" error.<br><br>Increasing `max_connections` excessively (e.g., to 5000) will exhaust OS memory and crash the server. The correct DBA solution is implementing a connection pooler like PgBouncer.", "Topic": "Troubleshooting", "Tags": "edb_postgres troubleshooting connections"},
    {"Question": "What is the primary function of `pg_restore`?", "Answer": "<b>ANSWER:</b> Restoring a database from a custom-format dump.<br><br>If you use `pg_dump` with the `-F c` (custom) or `-F d` (directory) format, you must use `pg_restore` to read it. The benefit is `pg_restore` can restore tables in parallel (`-j` flag) and allows you to selectively restore single tables.", "Topic": "Backup & Recovery", "Tags": "edb_postgres backup restore"},
    {"Question": "What is the `pg_waldump` utility?", "Answer": "<b>ANSWER:</b> A forensic tool to read Write-Ahead Log files.<br><br>WAL files are binary and unreadable. `pg_waldump` translates them into human-readable text. DBAs use it to figure out exactly what transaction caused massive WAL generation (e.g., \"Who deleted 50 million rows last night?\").", "Topic": "Troubleshooting", "Tags": "edb_postgres troubleshooting waldump"},
    {"Question": "What is `pg_rewind`?", "Answer": "<b>ANSWER:</b> A tool to resynchronize a demoted Primary after a failover.<br><br>If the Primary crashes, a Standby takes over. When the old Primary comes back, its data timeline has diverged. Instead of deleting the old Primary and doing a massive `pg_basebackup`, `pg_rewind` only copies the specific data blocks that changed, bringing it back as a Standby in seconds.", "Topic": "High Availability", "Tags": "edb_postgres ha pg_rewind"},
    {"Question": "What is the difference between `DELETE` and `TRUNCATE`?", "Answer": "<b>ANSWER:</b> MVCC overhead vs File deletion.<br><br>• <b>`DELETE`</b>: Scans the table and marks rows as dead (MVCC). Generates massive WAL logs and requires VACUUM later to free space.<br>• <b>`TRUNCATE`</b>: Physically deletes the underlying data file on the hard drive and creates a new empty one. It is instantaneous and reclaims all space immediately, but cannot be rolled back easily in all dialects.", "Topic": "SQL Fundamentals", "Tags": "edb_postgres sql truncate delete"},
    {"Question": "Explain the role of `search_path`.", "Answer": "<b>ANSWER:</b> Determines the order Postgres searches schemas when you query a table without specifying the schema name.<br><br>Default is `\"$user\", public`. If you query `SELECT * FROM users;`, it first looks in a schema named after your username. If it doesn't find it, it looks in the `public` schema.", "Topic": "Configuration", "Tags": "edb_postgres config schemas"},
    {"Question": "What is a Hash Index?", "Answer": "<b>ANSWER:</b> An index optimized exclusively for exact equality (`=`) checks.<br><br>Historically, they were unsafe in Postgres because they weren't WAL-logged (they would break on crash). In Postgres 10+, they became WAL-logged and crash-safe. They are smaller and slightly faster than B-Trees for simple '=' lookups.", "Topic": "Advanced Indexing", "Tags": "edb_postgres indexing hash"},
    {"Question": "What is an Anonymous Code Block in PL/pgSQL?", "Answer": "<b>ANSWER:</b> A PL/pgSQL script executed on the fly without saving it as a function.<br><br>Defined using the `DO $$ ... $$` syntax. Perfect for one-off DBA maintenance scripts or complex data migrations that require variables and loops, but don't need to be saved in the database permanently.", "Topic": "PL/pgSQL", "Tags": "edb_postgres plpgsql anonymous_block"},
    {"Question": "What does the `COMMIT` statement actually guarantee?", "Answer": "<b>ANSWER:</b> Durability (the 'D' in ACID).<br><br>When the client receives the \"COMMIT successful\" message, it guarantees that the transaction's WAL records have been physically flushed (fsync'd) to the persistent storage drive. Even if power is lost one millisecond later, the data will survive.", "Topic": "Architecture", "Tags": "edb_postgres architecture acid commit"}
]

with open('d:/all_codes/anki_cs_it_decks/edb_postgres_deck.csv', 'a', newline='', encoding='utf-8') as f:
    writer = csv.DictWriter(f, fieldnames=["Question", "Answer", "Topic", "Tags"])
    for card in cards:
        writer.writerow(card)

print(f"Appended {len(cards)} extra cards to the deck.")
