import csv

cards = [
    # Topic: Configuration (postgresql.conf)
    {"Question": "What is the role of `postgresql.conf`?", "Answer": "<b>ANSWER:</b> The main configuration file for the Postgres database cluster.<br><br>It contains all the core parameters like `shared_buffers`, `work_mem`, `max_connections`, and logging settings. Changes require either a server reload (`SELECT pg_reload_conf();`) or a full restart depending on the parameter.", "Topic": "Postgres Configuration", "Tags": "edb_postgres config postgresql_conf"},
    {"Question": "What is `pg_hba.conf` used for?", "Answer": "<b>ANSWER:</b> Host-Based Authentication configuration.<br><br>It acts as the firewall/bouncer for Postgres. It determines which IP addresses/subnets can connect, to which databases, using which user roles, and what authentication method (e.g., `md5`, `scram-sha-256`, `peer`, `cert`) they must use.", "Topic": "Postgres Configuration", "Tags": "edb_postgres config security pg_hba"},
    {"Question": "What does the `listen_addresses` parameter do?", "Answer": "<b>ANSWER:</b> Determines which network interfaces Postgres listens on.<br><br>• `localhost` (default): Only local connections allowed.<br>• `*`: Listens on all available IP interfaces.<br>Requires a database restart to take effect.", "Topic": "Postgres Configuration", "Tags": "edb_postgres config network"},
    {"Question": "Explain the `shared_buffers` parameter.", "Answer": "<b>ANSWER:</b> The amount of memory dedicated for caching data blocks (pages).<br><br><b>Rule of Thumb:</b> Typically set to 25% of total system RAM. It is where Postgres stores recently accessed data to avoid slow disk I/O. If a page isn't in `shared_buffers`, Postgres relies on the OS page cache.", "Topic": "Postgres Configuration", "Tags": "edb_postgres config memory tuning"},
    {"Question": "What is `work_mem` and why is it dangerous to set it too high?", "Answer": "<b>ANSWER:</b> Memory used for sorting (ORDER BY) and hashing (hash joins) operations.<br><br><b>The Danger:</b> It is allocated <i>per operation</i>, not globally. If `work_mem` is 100MB, and a complex query has 5 sort operations, that single query uses 500MB. If 100 users run it, it consumes 50GB, leading to Out Of Memory (OOM) crashes.", "Topic": "Postgres Configuration", "Tags": "edb_postgres config memory tuning"},
    {"Question": "What does `maintenance_work_mem` control?", "Answer": "<b>ANSWER:</b> Memory used for maintenance operations like `VACUUM`, `CREATE INDEX`, and `ALTER TABLE`.<br><br>Since these are executed less frequently and usually by DBAs, this can be set much higher than `work_mem` (e.g., 1GB - 2GB) to speed up index creation and vacuuming.", "Topic": "Postgres Configuration", "Tags": "edb_postgres config memory vacuum"},
    {"Question": "How do you reload configuration changes without restarting the database?", "Answer": "<b>ANSWER:</b> Using the SQL function or system command.<br><br><b>SQL:</b><br><code>SELECT pg_reload_conf();</code><br><br><b>Linux OS:</b><br><code>systemctl reload postgresql-15</code> or <code>pg_ctl reload -D /path/to/data</code>", "Topic": "Postgres Configuration", "Tags": "edb_postgres config admin commands"},
    {"Question": "What is the difference between `postgresql.conf` and `postgresql.auto.conf`?", "Answer": "<b>ANSWER:</b> Manual vs ALTER SYSTEM.<br><br>• `postgresql.conf`: Edited manually by the DBA.<br>• `postgresql.auto.conf`: Edited automatically when a DBA runs the SQL command <code>ALTER SYSTEM SET param = value;</code>. It always overrides the manual `postgresql.conf`.", "Topic": "Postgres Configuration", "Tags": "edb_postgres config admin"},
    
    # Topic: Storage & Clusters
    {"Question": "What is a 'Database Cluster' in Postgres?", "Answer": "<b>ANSWER:</b> A single instance of a running database server managing multiple databases.<br><br>Unlike standard English where 'cluster' means multiple servers, in Postgres, it means one server process managing a single data directory (`PGDATA`) that holds multiple independent databases (e.g., HR_db, Sales_db).", "Topic": "Storage & Clusters", "Tags": "edb_postgres architecture cluster"},
    {"Question": "What is the role of `initdb`?", "Answer": "<b>ANSWER:</b> It initializes a brand new Postgres Database Cluster.<br><br>It creates the base directory structure, system catalogs, the default `postgres` database, the WAL directories, and the initial configuration files (`postgresql.conf`, `pg_hba.conf`).", "Topic": "Storage & Clusters", "Tags": "edb_postgres installation initdb"},
    {"Question": "What is a 'Tablespace' in Postgres?", "Answer": "<b>ANSWER:</b> A named location (folder on disk) where database objects can be stored.<br><br><b>Use Case:</b> You have a fast, expensive NVMe SSD, and a slow, cheap HDD. You create a Tablespace pointing to the SSD for hot indexes, and a Tablespace pointing to the HDD for old archive tables.", "Topic": "Storage & Clusters", "Tags": "edb_postgres architecture tablespace"},
    {"Question": "How do you create a tablespace in Postgres?", "Answer": "<b>ANSWER:</b> Provide a name and an absolute directory path.<br><br><b>The Code:</b><br><code>CREATE TABLESPACE fast_ssd LOCATION '/mnt/ssd1/pg_data';</code><br><br>The OS user (`postgres` or `enterprisedb`) must have read/write permissions on that directory.", "Topic": "Storage & Clusters", "Tags": "edb_postgres tablespace sql"},
    {"Question": "What are System Catalogs?", "Answer": "<b>ANSWER:</b> The Postgres Data Dictionary (Metadata).<br><br>They are regular relational tables that store information about tables, columns, indexes, roles, and privileges. They begin with `pg_` (e.g., `pg_class`, `pg_attribute`, `pg_roles`).", "Topic": "Storage & Clusters", "Tags": "edb_postgres catalogs metadata"},
    {"Question": "What does the `pg_class` catalog store?", "Answer": "<b>ANSWER:</b> Information about all relation-like objects.<br><br>It tracks tables, indexes, sequences, and views. Crucial columns include `relname` (the name), `relpages` (size in pages), and `reltuples` (estimated number of rows).", "Topic": "Storage & Clusters", "Tags": "edb_postgres catalogs tables"},
    {"Question": "What is the `OID` in Postgres storage?", "Answer": "<b>ANSWER:</b> Object Identifier.<br><br>Every database, table, and index has a unique internal integer ID. Under the hood, Postgres doesn't name files `users_table.db`, it names them with their OID (e.g., `/base/16384/24567`), where 16384 is the Database OID and 24567 is the Table OID.", "Topic": "Storage & Clusters", "Tags": "edb_postgres storage oid"},
    
    # Topic: Security
    {"Question": "What is a Role in Postgres?", "Answer": "<b>ANSWER:</b> A User or a Group.<br><br>Postgres doesn't strictly distinguish between 'Users' and 'Groups'. A Role can log in (User) or simply act as a container for privileges (Group).<br><code>CREATE ROLE analyst LOGIN PASSWORD '123';</code>", "Topic": "Database Security", "Tags": "edb_postgres security roles"},
    {"Question": "How do you grant Read-Only access to a table?", "Answer": "<b>ANSWER:</b> Using the GRANT command.<br><br><b>The Code:</b><br><code>GRANT SELECT ON TABLE users TO analyst;</code><br><br>To grant read access to ALL tables in a schema:<br><code>GRANT SELECT ON ALL TABLES IN SCHEMA public TO analyst;</code>", "Topic": "Database Security", "Tags": "edb_postgres security privileges"},
    {"Question": "What is Row-Level Security (RLS)?", "Answer": "<b>ANSWER:</b> Restricting access to specific rows based on the user's role.<br><br><b>Example:</b> A manager can only `SELECT` rows in the `Sales` table where `region = 'North'`.<br>You enable it via <code>ALTER TABLE Sales ENABLE ROW LEVEL SECURITY;</code> and then define a `CREATE POLICY`.", "Topic": "Database Security", "Tags": "edb_postgres security rls"},
    {"Question": "What is the `pg_stat_statements` extension used for?", "Answer": "<b>ANSWER:</b> Tracking query performance statistics.<br><br>It records how many times a specific SQL query was executed, total execution time, min/max times, and memory used. It is the #1 tool for finding the slowest queries dragging down the database.", "Topic": "Monitoring & Admin", "Tags": "edb_postgres monitoring tuning"},
    {"Question": "How do you find long-running queries currently executing?", "Answer": "<b>ANSWER:</b> Query the `pg_stat_activity` view.<br><br><b>The Code:</b><br><code>SELECT pid, usename, state, query, now() - query_start AS duration <br>FROM pg_stat_activity <br>WHERE state = 'active' <br>AND now() - query_start > interval '5 minutes';</code>", "Topic": "Monitoring & Admin", "Tags": "edb_postgres monitoring queries"}
]

with open('d:/all_codes/anki_cs_it_decks/edb_postgres_deck.csv', 'a', newline='', encoding='utf-8') as f:
    writer = csv.DictWriter(f, fieldnames=["Question", "Answer", "Topic", "Tags"])
    for card in cards:
        writer.writerow(card)

print(f"Appended {len(cards)} cards from Part 2 to the deck.")
