import csv

cards = [
    # SQL Primer & Advanced SQL
    {"Question": "What is a Common Table Expression (CTE)?", "Answer": "<b>ANSWER:</b> A temporary result set that you can reference within another SQL statement.<br><br><b>The Code:</b><br><code>WITH regional_sales AS (<br>  SELECT region, SUM(amount) as total_sales FROM orders GROUP BY region<br>)<br>SELECT * FROM regional_sales WHERE total_sales > 10000;</code><br><br>It makes complex queries much more readable compared to nested subqueries.", "Topic": "Advanced SQL", "Tags": "edb_postgres sql cte"},
    {"Question": "What is a Window Function in SQL?", "Answer": "<b>ANSWER:</b> A function that performs a calculation across a set of table rows that are somehow related to the current row, <i>without</i> grouping them into a single output row.<br><br><b>Example:</b><br><code>SELECT name, salary, AVG(salary) OVER (PARTITION BY department) FROM employees;</code><br>This shows each employee's salary alongside the average salary of their department.", "Topic": "Advanced SQL", "Tags": "edb_postgres sql window_function"},
    {"Question": "What is the difference between `UNION` and `UNION ALL`?", "Answer": "<b>ANSWER:</b> Duplicates.<br><br>• <b>`UNION`</b>: Combines the result sets of two queries and <b>removes</b> duplicate rows. It requires a sort operation (which is slow).<br>• <b>`UNION ALL`</b>: Combines the result sets and <b>keeps</b> duplicates. It is much faster because it doesn't need to sort and deduplicate.", "Topic": "SQL Fundamentals", "Tags": "edb_postgres sql union"},
    {"Question": "How does `UPSERT` work in Postgres?", "Answer": "<b>ANSWER:</b> Using the `ON CONFLICT` clause.<br><br>It attempts to INSERT a row. If it violates a unique constraint (like an ID already exists), it performs an UPDATE instead.<br><br><b>The Code:</b><br><code>INSERT INTO users (id, name) VALUES (1, 'John')<br>ON CONFLICT (id) DO UPDATE SET name = 'John';</code>", "Topic": "Advanced SQL", "Tags": "edb_postgres sql upsert"},
    {"Question": "What is a `LATERAL` join?", "Answer": "<b>ANSWER:</b> A join that allows a subquery in the FROM clause to reference columns from preceding items in the FROM clause.<br><br>It's like a 'foreach' loop in SQL. For every row in the left table, it executes the right subquery passing in values from the left row.", "Topic": "Advanced SQL", "Tags": "edb_postgres sql joins lateral"},
    {"Question": "What is a Materialized View?", "Answer": "<b>ANSWER:</b> A view that caches its result set physically on disk.<br><br>Standard views just save the SQL query. Materialized Views actually run the query and store the data, making reads lightning fast for complex aggregations. You must manually refresh them using <code>REFRESH MATERIALIZED VIEW my_view;</code>", "Topic": "Advanced SQL", "Tags": "edb_postgres sql materialized_view"},
    
    # PL/pgSQL & Extensions
    {"Question": "What is PL/pgSQL?", "Answer": "<b>ANSWER:</b> Postgres's Procedural Language.<br><br>It extends standard SQL by adding control structures like `IF`, `WHILE`, `FOR` loops, and variables. It is used to write powerful Stored Procedures, Functions, and Triggers.", "Topic": "PL/pgSQL", "Tags": "edb_postgres plpgsql"},
    {"Question": "What is the difference between a Function and a Procedure in Postgres 11+?", "Answer": "<b>ANSWER:</b> Transaction control.<br><br>• <b>Function:</b> Cannot commit or rollback transactions inside itself. Usually returns a value.<br>• <b>Procedure:</b> Can execute <code>COMMIT;</code> and <code>ROLLBACK;</code> inside its body. Does not return a value. Invoked using <code>CALL my_procedure();</code> instead of `SELECT`.", "Topic": "PL/pgSQL", "Tags": "edb_postgres plpgsql procedure function"},
    {"Question": "What is a Trigger in Postgres?", "Answer": "<b>ANSWER:</b> A function that is automatically invoked by the database in response to specific events (INSERT, UPDATE, DELETE, TRUNCATE) on a table.<br><br>They can run `BEFORE` or `AFTER` the event. Often used for auditing (e.g., logging who changed a row) or enforcing complex business rules.", "Topic": "PL/pgSQL", "Tags": "edb_postgres plpgsql trigger"},
    {"Question": "What is `postgres_fdw`?", "Answer": "<b>ANSWER:</b> Foreign Data Wrapper.<br><br>An extension that allows you to access tables stored in a <i>completely different</i> Postgres database server as if they were local tables. You can join a local table with a remote table seamlessly.", "Topic": "Extensions", "Tags": "edb_postgres extensions fdw"},
    {"Question": "What is the `pg_cron` extension?", "Answer": "<b>ANSWER:</b> A simple cron-based job scheduler that runs inside the database.<br><br>It allows DBAs to schedule tasks like `VACUUM`, `REFRESH MATERIALIZED VIEW`, or data aggregations using standard cron syntax directly in SQL.<br><code>SELECT cron.schedule('0 2 * * *', 'VACUUM ANALYZE users');</code>", "Topic": "Extensions", "Tags": "edb_postgres extensions cron"},

    # Data Loading
    {"Question": "What is the fastest way to load a massive amount of data into Postgres?", "Answer": "<b>ANSWER:</b> The `COPY` command.<br><br>It is highly optimized for bulk data loading directly from a CSV or text file. It is exponentially faster than running millions of individual `INSERT` statements.<br><code>COPY users FROM '/tmp/users.csv' DELIMITER ',' CSV;</code>", "Topic": "Data Loading", "Tags": "edb_postgres copy data_loading"},
    {"Question": "What is the difference between `COPY` and `\\copy` in psql?", "Answer": "<b>ANSWER:</b> Where the file lives.<br><br>• <b>`COPY`</b>: An SQL command. The file must exist on the <b>Database Server</b>, and the Postgres OS user must have read permissions to it.<br>• <b>`\\copy`</b>: A psql meta-command. The file exists on the <b>Client Machine</b> running psql, and the data is streamed over the network to the server.", "Topic": "Data Loading", "Tags": "edb_postgres copy psql"},

    # Transactions & Locking
    {"Question": "What is MVCC (Multi-Version Concurrency Control)?", "Answer": "<b>ANSWER:</b> Postgres's method for handling concurrent transactions without locking.<br><br><b>\"Readers don't block writers, and writers don't block readers.\"</b> When you UPDATE a row, Postgres creates a brand new version of that row. Other transactions keep reading the old version until your transaction COMMITs.", "Topic": "Architecture", "Tags": "edb_postgres architecture mvcc"},
    {"Question": "What is a Deadlock?", "Answer": "<b>ANSWER:</b> When two transactions block each other indefinitely.<br><br>• Tx1 locks Row A, wants Row B.<br>• Tx2 locks Row B, wants Row A.<br>Neither can proceed. Postgres detects this automatically after `deadlock_timeout` (default 1s), kills one of the transactions, and rolls it back.", "Topic": "Architecture", "Tags": "edb_postgres architecture locking deadlock"},
    {"Question": "What is the `pg_locks` view used for?", "Answer": "<b>ANSWER:</b> Viewing all active locks in the database.<br><br>DBAs use it alongside `pg_stat_activity` to figure out which query is blocking other queries. (e.g., if a developer accidentally started a transaction, locked a table, and went to lunch without committing).", "Topic": "Monitoring & Admin", "Tags": "edb_postgres monitoring locks"},

    # Indexing
    {"Question": "What is a B-Tree Index?", "Answer": "<b>ANSWER:</b> The default index type in Postgres.<br><br>It is a balanced tree highly optimized for most common queries, including equality (`=`) and range (`>`, `<`, `BETWEEN`) comparisons. If you just type `CREATE INDEX`, you get a B-Tree.", "Topic": "Indexing", "Tags": "edb_postgres indexing btree"},
    {"Question": "What is a GIN Index used for?", "Answer": "<b>ANSWER:</b> Generalized Inverted Index.<br><br>Highly optimized for columns that contain <b>multiple values</b>, such as Arrays or JSONB documents, or for Full-Text Search. It is excellent at querying \"Does this array contain this specific item?\"", "Topic": "Indexing", "Tags": "edb_postgres indexing gin jsonb"},
    {"Question": "What is a Partial Index?", "Answer": "<b>ANSWER:</b> An index built on only a subset of a table's rows.<br><br><b>Example:</b> If you have a massive `orders` table, but 99% of queries only search for 'Unshipped' orders, you can create a tiny, lightning-fast index:<br><code>CREATE INDEX idx_unshipped ON orders (customer_id) WHERE status = 'Unshipped';</code>", "Topic": "Indexing", "Tags": "edb_postgres indexing partial"},
    {"Question": "Why should you use `CREATE INDEX CONCURRENTLY` in production?", "Answer": "<b>ANSWER:</b> To avoid locking out writes.<br><br>A standard `CREATE INDEX` locks the table against writes (INSERT/UPDATE/DELETE) while the index builds. `CONCURRENTLY` builds the index in the background without blocking writes, though it takes slightly longer to finish.", "Topic": "Indexing", "Tags": "edb_postgres indexing concurrently"}
]

with open('d:/all_codes/anki_cs_it_decks/edb_postgres_deck.csv', 'a', newline='', encoding='utf-8') as f:
    writer = csv.DictWriter(f, fieldnames=["Question", "Answer", "Topic", "Tags"])
    for card in cards:
        writer.writerow(card)

print(f"Appended {len(cards)} cards from Part 4 to the deck.")
