import csv

cards = [
    # Table Partitioning
    {"Question": "What is Table Partitioning in Postgres?", "Answer": "<b>ANSWER:</b> Splitting one large logical table into smaller physical pieces (partitions).<br><br>Users query the 'parent' table normally, but Postgres routes the query only to the relevant 'child' partitions (Partition Pruning). This massively improves performance for huge tables (e.g., millions of rows) by scanning less data and making indexes smaller.", "Topic": "Advanced DBA", "Tags": "edb_postgres partitioning table"},
    {"Question": "What are the three types of Declarative Partitioning in Postgres?", "Answer": "<b>ANSWER:</b> Range, List, and Hash.<br><br>1. <b>Range:</b> Partitioning by a continuous range of values (e.g., Dates: `partition_2023`, `partition_2024`).<br>2. <b>List:</b> Partitioning by exact discrete values (e.g., Country: `part_usa`, `part_uk`).<br>3. <b>Hash:</b> Distributing rows evenly across a fixed number of partitions based on a hash of the key.", "Topic": "Advanced DBA", "Tags": "edb_postgres partitioning types"},
    {"Question": "What is Partition Pruning?", "Answer": "<b>ANSWER:</b> A query optimization technique where the planner ignores partitions that cannot possibly contain the requested data.<br><br>If a table is partitioned by year, and you query `WHERE order_date = '2023-05-01'`, the planner 'prunes' (skips) all the 2022 and 2024 partitions, saving massive I/O.", "Topic": "Advanced DBA", "Tags": "edb_postgres partitioning tuning"},

    # High Availability (HA) Tooling
    {"Question": "What is Connection Pooling, and why is PgBouncer widely used?", "Answer": "<b>ANSWER:</b> Reusing a small number of database connections for a large number of clients.<br><br>Postgres creates a heavy OS process for every connection. If 5,000 clients connect directly, the server will crash due to memory exhaustion. <b>PgBouncer</b> sits in front, accepts the 5,000 lightweight client connections, and routes them through just 100 actual heavy Postgres connections.", "Topic": "High Availability", "Tags": "edb_postgres ha pgbouncer connection_pooling"},
    {"Question": "What is Patroni?", "Answer": "<b>ANSWER:</b> A template for High Availability (HA) Postgres clusters.<br><br>It uses a Distributed Configuration Store (like etcd, Consul, or ZooKeeper) to manage a Postgres cluster. If the Primary node dies, Patroni detects it, automatically promotes the best Standby to Primary, and updates the network routing.", "Topic": "High Availability", "Tags": "edb_postgres ha patroni failover"},
    {"Question": "What is `repmgr`?", "Answer": "<b>ANSWER:</b> Replication Manager for Postgres.<br><br>A popular open-source tool suite that simplifies the administration of Postgres streaming replication clusters. It handles cloning standby servers (`repmgr standby clone`) and managing manual or automatic failover.", "Topic": "High Availability", "Tags": "edb_postgres ha repmgr replication"},

    # Advanced Backup
    {"Question": "What is pgBackRest?", "Answer": "<b>ANSWER:</b> A highly scalable, parallel backup and restore tool for Postgres.<br><br>Unlike basic `pg_basebackup`, it supports parallel compression/decompression across multiple CPU cores, differential/incremental backups, and direct backups to S3/Cloud storage. It is the industry standard for large Postgres databases.", "Topic": "Backup & Recovery", "Tags": "edb_postgres backup pgbackrest"},
    {"Question": "What is the difference between a Full, Differential, and Incremental backup in pgBackRest?", "Answer": "<b>ANSWER:</b> How much data is copied.<br><br>• <b>Full:</b> Copies every file in the database cluster.<br>• <b>Differential:</b> Copies only files that changed since the <i>last Full</i> backup.<br>• <b>Incremental:</b> Copies only files that changed since the <i>last backup of any type</i> (Full, Diff, or Incr).", "Topic": "Backup & Recovery", "Tags": "edb_postgres backup pgbackrest types"},

    # EDB Advanced Server Specifics
    {"Question": "What is the EDB Postgres Resource Manager?", "Answer": "<b>ANSWER:</b> A tool to control CPU and I/O consumption by user or group.<br><br>In standard Postgres, a bad query can eat 100% CPU. EDB Advanced Server allows DBAs to create 'Resource Groups' (e.g., 'Analyst_Group') and hard-limit them to, say, 20% CPU, ensuring production transactions are never starved.", "Topic": "EDB Advanced Server", "Tags": "edb_postgres advanced resource_manager"},
    {"Question": "What is EDB SQL Profiler?", "Answer": "<b>ANSWER:</b> A tool to trace and diagnose slow SQL queries in real-time.<br><br>It integrates with Postgres Enterprise Manager (PEM) to capture query execution statistics, execution plans, and wait events to help DBAs pinpoint exactly where a query is spending its time.", "Topic": "EDB Advanced Server", "Tags": "edb_postgres advanced profiling tuning"},
    {"Question": "What is EDB Postgres Enterprise Manager (PEM)?", "Answer": "<b>ANSWER:</b> A centralized, web-based management and monitoring console.<br><br>It provides a single pane of glass to monitor hundreds of Postgres instances, offering custom dashboards, alerting, capacity planning, and automated maintenance scheduling.", "Topic": "EDB Advanced Server", "Tags": "edb_postgres advanced pem monitoring"},
    {"Question": "What are EDB Wait States?", "Answer": "<b>ANSWER:</b> Detailed diagnostics showing exactly what a process is waiting for.<br><br>While community Postgres has `pg_stat_activity.wait_event`, EDB provides deeper Oracle-style wait state views (like `edb_wait_states`) that historicalize wait data over time (e.g., CPU, Disk I/O, Locks) for forensic tuning.", "Topic": "EDB Advanced Server", "Tags": "edb_postgres advanced tuning wait_states"},
    {"Question": "Does EDB Advanced Server support Oracle PL/SQL natively?", "Answer": "<b>ANSWER:</b> Yes. It includes a native PL/SQL engine (SPL - Stored Procedure Language).<br><br>This allows Oracle stored procedures, functions, packages, and triggers to run directly on EDB Postgres with little to no modification, massively simplifying Oracle-to-Postgres migrations.", "Topic": "EDB Advanced Server", "Tags": "edb_postgres advanced oracle_compatibility"},

    # Security & Auditing
    {"Question": "What is `pgAudit`?", "Answer": "<b>ANSWER:</b> PostgreSQL Audit Extension.<br><br>It provides detailed, standard-compliant session and object auditing. Instead of just logging text to a file, it structure logs exactly what SQL was executed by whom, which is often required for compliance (HIPAA, PCI, SOX).", "Topic": "Database Security", "Tags": "edb_postgres security pgaudit compliance"},
    {"Question": "How do you enforce SSL/TLS encryption for database connections?", "Answer": "<b>ANSWER:</b> In `postgresql.conf` and `pg_hba.conf`.<br><br>1. Set `ssl = on` in `postgresql.conf` and provide the cert/key paths.<br>2. In `pg_hba.conf`, change the connection type from `host` to `hostssl`.<br>This forces clients to use an encrypted connection.", "Topic": "Database Security", "Tags": "edb_postgres security ssl networking"},
    {"Question": "What is SCRAM-SHA-256?", "Answer": "<b>ANSWER:</b> The modern, secure password authentication method for Postgres.<br><br>It replaced the old, insecure `md5` method. It prevents password sniffing on the network and prevents replay attacks. You set it via `password_encryption = scram-sha-256` in `postgresql.conf`.", "Topic": "Database Security", "Tags": "edb_postgres security passwords authentication"},
    {"Question": "What does the `peer` authentication method do in `pg_hba.conf`?", "Answer": "<b>ANSWER:</b> It relies on the operating system's user identity.<br><br>If the Linux user logged into the server is `alice`, and `peer` auth is set, she can automatically log into the database as the Postgres role `alice` without providing a database password. Typically used for local connections.", "Topic": "Database Security", "Tags": "edb_postgres security pg_hba peer"},

    # System Catalog deep dive
    {"Question": "What is the difference between `pg_stat_user_tables` and `pg_stat_all_tables`?", "Answer": "<b>ANSWER:</b> Filtering out system tables.<br><br>`pg_stat_user_tables` shows statistics (like number of sequential scans, rows inserted, dead tuples) ONLY for tables created by users. `pg_stat_all_tables` includes internal Postgres system catalogs and TOAST tables.", "Topic": "Monitoring & Admin", "Tags": "edb_postgres catalogs monitoring"},
    {"Question": "What is TOAST in Postgres?", "Answer": "<b>ANSWER:</b> The Oversized-Attribute Storage Technique.<br><br>Postgres has a strict 8KB page size. If a single row exceeds this (e.g., saving a massive text document or JSON blob), Postgres automatically compresses and chunks the oversized data into a hidden 'TOAST' table, keeping the main table small and fast.", "Topic": "Architecture", "Tags": "edb_postgres architecture storage toast"},
    {"Question": "What is the `pg_settings` view?", "Answer": "<b>ANSWER:</b> A system view that shows the current values of all configuration parameters.<br><br>It is the SQL equivalent of reading `postgresql.conf`, but better. It shows the current value, the default value, the min/max allowed, and whether a restart is required to change it.", "Topic": "Monitoring & Admin", "Tags": "edb_postgres config monitoring"}
]

with open('d:/all_codes/anki_cs_it_decks/edb_postgres_deck.csv', 'a', newline='', encoding='utf-8') as f:
    writer = csv.DictWriter(f, fieldnames=["Question", "Answer", "Topic", "Tags"])
    for card in cards:
        writer.writerow(card)

print(f"Appended {len(cards)} cards from Part 5 to the deck.")
